### ISSUE TITLE
 Environment.updater no longer supports False value

### ISSUE THREAD

**Issue by kmike** [miracle2k/webassets#51]
According to http://elsdoerfer.name/docs/webassets/django/settings.html ASSETS_UPDATER can be False. This used to work with webassets 0.5 but with latest master an exception is raised (Caught AttributeError while rendering: 'NoneType' object has no attribute 'needs_rebuild'). This is not mentioned in [upgrading docs](https://github.com/miracle2k/webassets/blob/master/docs/upgrading.rst).
